### ISSUE TITLE
request: recurring to fund AWS-VMs for integration tests

### ISSUE THREAD

**Issue by medyagh** [kubernetes/funding#10]
I don't have estimates but we do minikube testing in different clouds, gcloud, azure, but we don't have any testing in AWS. AWS-VMs for minikube testing with up to 10 bare-metal VMs for testing different hypervisors.

**Comment by dims** [comment]
Ack @medyagh will ask wg-k8s-infra first

**Comment by dims** [comment]
Talked to @medyagh . The pattern minikube is following is to have persistent VMs in various clouds that act as github action runners. And github actions trigger things to run in those persistent VM(s). So we should basically get some AWS credits/credentials that @medyagh can share with minikube maintainers to be able to take care of this farm of VMs.

@idvoretskyi already indicated that CNCF can support this, so i will open a service desk ticket to get the process rolling

**Comment by idvoretskyi** [comment]
@dims sorry, I don't understand why specifically AWS is needed here - can you explain with more details?

We can offer the host to run GHA runners in Packet, or negotiate some extra capacity for the SaaS GitHub Actions.

**Comment by dims** [comment]
@idvoretskyi minikube has features that work with various cloud providers ( example the registry integration https://github.com/kubernetes/minikube/blob/master/site/content/en/docs/handbook/registry.md#using-a-private-registry ) that needs to be tested. They currently have cloud credits from Microsoft/Azure for some of the scenarios (include windows testing as well). So there are things that need to be tested per cloud provider. Hence the ask for specific cloud credits.

**Comment by medyagh** [comment]
The current goal is to have testing in all public clouds in github actions.
we use azure for nested virtualizaton testing in Windows, 
and we would like to add github actions for different Linux distros available on AWS.
also to host the kic-base image that on aws registry 

also we are interested to try the metal service on aws, that would let us try the virtualization testing on metal (instead of vm inside vm) https://aws.amazon.com/blogs/compute/running-hyper-v-on-amazon-ec2-bare-metal-instances/

**Comment by dims** [comment]
@idvoretskyi @medyagh i've opened a Service Desk ticket https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-434 

thanks,
Dims

**Comment by medyagh** [comment]
> @idvoretskyi @medyagh i've opened a Service Desk ticket https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-434
> 
> thanks,
> Dims

thank you @dims is this service desk protal something that I could login to ? or is it internal access only?

**Comment by dims** [comment]
@medyagh i'll update you when there's traffic there, at this point, we it's assigned to Ihor which in Europe. So we wait for Ihor.

**Comment by idvoretskyi** [comment]
@medyagh it's for the CNCF project maintainers only - https://github.com/cncf/servicedesk#how-do-i-file-a-ticket-with-the-service-desk.

@dims and I will take it from there.

**Comment by dims** [comment]
@medyagh Can you please the AWS pricing calculators and get us an approximately monthly cost?

**Comment by medyagh** [comment]
Thanks @dims here is the link for the estimate https://calculator.aws/#/estimate?id=ce22ca6a1ce5fc79314fb57d26b5fc79388c8fd6

- Picked 10 instances of type" i3.2xlarge" bare metal with 8 Logical CPUs.
- Picked  "Windows" for the OS in the quick calculator. but in practice half them will become linux instances.

**Comment by idvoretskyi** [comment]
> Picked "Windows" for the OS in the quick calculator. but in practice half them will become linux instances.

@medyagh I'd suggest you put more clear estimates here, the price can differ significantly.

**Comment by medyagh** [comment]
> > Picked "Windows" for the OS in the quick calculator. but in practice half them will become linux instances.
> 
> @medyagh I'd suggest you put more clear estimates here, the price can differ significantly.

@idvoretskyi 
here is the updated caclucator 5 linux and 5 windows i3.xlarge, 4 CPUs and 32 GB Ram 

https://calculator.aws/#/estimate?id=92101f22c642b5445b89ba83486c468160b09415

**Comment by medyagh** [comment]
Hi @dims @idvoretskyi I would like to know if there is any follow up on this ?

**Comment by dims** [comment]
it's End of week for sure for Ihor. let's pick this back up next week.

**Comment by medyagh** [comment]
Hi there is there any update  @dims @idvoretskyi

**Comment by idvoretskyi** [comment]
Status update: there are no AWS credits available yet, so this is pending. We are waiting for the next batch of credits to be allocated by AWS, and we'll proceed from there.

Should take a week or a few (hopefully).

**Comment by dims** [comment]
this is already done.

thanks,
Dims
