### ISSUE TITLE
request: recurring ?/month to fund storage for AWS AMIs for kubernetes-sigs/cluster-api-provider-aws

### ISSUE THREAD

**Issue by ncdc** [kubernetes/funding#12]
- **Description**: CNCF-owned AWS account to host AMIs for kubernetes-sigs/cluster-api-provider-aws
- **Requesting SIG**: Cluster Lifecycle
- **SIG approval**: will ask the SIG leads to +1 this issue
- **Cost**: TBD (will try to get estimates of our current costs)
  - Frequency: monthly
  - Scale function: approximately $18USD/Kubernetes version/month * number of Kuberntes versions we have AMIs for, governed by https://aws.amazon.com/ebs/pricing/. EBS storage cost: $0.05 / GB / month. AMI size is 8GB, and we publish in 15 regions. Each Kubernetes version has 3 variants (Ubuntu, Centos, AL2).
- **SIG approval list archive URL**: N/A - see above
- **Owners for renewal**: N/A?
- **Cancellation criteria**: N/A?
- **Alternatives considered**: None

These AMIs are currently stored in a VMware AWS account. We want to move to a CNCF-owned account to be more accountable to and open to the community at large.

@randomvariable any chance you could track down our current approximate monthly costs for these AMIs?

xref https://github.com/kubernetes/k8s.io/issues/1116

**Comment by ncdc** [comment]
cc @timothysc @dims @neolit123 @idvoretskyi @nikhita

**Comment by neolit123** [comment]
+1

**Comment by neolit123** [comment]
cc @justinsb

**Comment by randomvariable** [comment]
Don't have access to the historic data, but it'll be $6 / AMI copied to all regions / month:

EBS storage cost: $0.05 / GB / month
AMI size is 8GB, and we publish in 15 regions.

**Comment by ncdc** [comment]
For a single Kubernetes version (e.g. 1.18.1), how many AMIs do we publish?

**Comment by randomvariable** [comment]
Sorry, updated my comment above. That's $6 for all AMIs in all of the regions. It's usually one set of AMIs per Kubernetes version.

**Comment by ncdc** [comment]
Does that cover ubuntu + centos + AL2 variants combined? Or is that $6 for ubuntu, $6 for centos, etc?

**Comment by randomvariable** [comment]
Beat me to it. That's per distribution, so more like $18 at present.

**Comment by nikhita** [comment]
/assign

I'll create a CNCF service desk ticket to get this moving. As @idvoretskyi mentioned on slack, CNCF is temporary out of credits on the CNCF AWS account but are hoping to get that resolved in the next week or two.

**Comment by justinsb** [comment]
+1 from me

**Comment by nikhita** [comment]
Created service desk ticket - https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-492. It's only accessible to steering committee members and CNCF staff, but I'll post updates here as I hear back on the service desk ticket. :+1:

**Comment by idvoretskyi** [comment]
@ncdc we are unblocked on this now, so please proceed!

Anything I can help here with?

**Comment by ncdc** [comment]
@detiber @randomvariable @rudoi would you all be able to take point on this?

**Comment by ncdc** [comment]
(And thank you @idvoretskyi for the update!)

**Comment by nikhita** [comment]
@ncdc @detiber @randomvariable @rudoi :wave: Are there any outstanding items here? Can this issue be closed?

**Comment by ncdc** [comment]
@nikhita I do believe this can be closed. @idvoretskyi was able to get us access to a CNCF AWS account and @sedefsavas is working on the implementation details. If we determine we're missing anything, we can reopen or create a new request. Thanks for following up!

/close
