### ISSUE TITLE
request: recurring to fund Alibaba account for minikube

### ISSUE THREAD

**Issue by RA489** [kubernetes/funding#14]
Currently I don't have estimates but we do minikube testing in different clouds, gcloud, azure, but we don't have any testing in Alibaba. 

Refs: https://github.com/kubernetes/minikube/issues/7695

**Comment by RA489** [comment]
cc @medyagh

**Comment by dims** [comment]
@resouer @idvoretskyi Are there there any Alibaba credits available for community work?

**Comment by idvoretskyi** [comment]
@dims CNCF doesn't have any yet.

How much is needed (total budget)?

**Comment by medyagh** [comment]
> @dims CNCF doesn't have any yet.
> 
> How much is needed (total budget)?

the estimate would depend on knowing how many downloads we get on traffic and how much it costs on alibaba.
currently minikube has 3 million downloads on github, we could start with guess estimate $2000 a mohth and from then we try to adjust the price if the are more downloads at that time

**Comment by dims** [comment]
@medyagh so this is just for images then?

**Comment by resouer** [comment]
I am not aware of any form of funding from Alibaba Cloud side but the container image service of Alibaba Cloud is indeed free.

An alternative is to use this minikube fork (which is actively maintained): https://github.com/AliyunContainerService/minikube

**Comment by medyagh** [comment]
@dims @resouer it would be for both Docker image and also minikube binaries and preload tar files . so we need a storage bucket as well as image repository for the container

**Comment by blueelvis** [comment]
@resouer - That fork seems to be 398 commits and 1 release behind of what is currently on the main repo.

**Comment by medyagh** [comment]
@dims @resouer a gentle reminder about this issue.

**Comment by idvoretskyi** [comment]
@medyagh a rough estimate in $$$ is strongly likely still.

**Comment by medyagh** [comment]
@idvoretskyi we would like to start with $3000 a month estimate then if needed update it.

**Comment by idvoretskyi** [comment]
@dims FYI ^

**Comment by medyagh** [comment]
@idvoretskyi is there any updates on this ?

**Comment by idvoretskyi** [comment]
@medyagh I think we are waiting for approval and formal request from the steering, not from me.

**Comment by dims** [comment]
@idvoretskyi @medyagh i dropped the ball on this. apologies. will get a response from steering in a few days. Personally i'd be +1 on this.

**Comment by idvoretskyi** [comment]
@dims thanks!

**Comment by liggitt** [comment]
That amount seems reasonable to me, but I'd like to understand the intended use better.

> it would be for both Docker image and also minikube binaries and preload tar files

> the estimate would depend on knowing how many downloads we get on traffic and how much it costs on alibaba.

Is this for running CI to test in that environment, or would this attract production/external traffic? I'd like to understand the implications if the traffic and costs turn out to be higher than expected. Will you be able to control those by reducing frequency/quantity of test jobs, or will the traffic be outside the project's control?

**Comment by dims** [comment]
@medyagh can you please confirm/respond?

**Comment by mrbobbytables** [comment]
One other thought, as this would be community owned infrastructure, has wg-k8s-infra been engaged about the long term stewardship of it?

**Comment by medyagh** [comment]
> That amount seems reasonable to me, but I'd like to understand the intended use better.
> 
> > it would be for both Docker image and also minikube binaries and preload tar files
> 
> > the estimate would depend on knowing how many downloads we get on traffic and how much it costs on alibaba.
> 
> Is this for running CI to test in that environment, or would this attract production/external traffic? I'd like to understand the implications if the traffic and costs turn out to be higher than expected. Will you be able to control those by reducing frequency/quantity of test jobs, or will the traffic be outside the project's control?

@liggitt 
@dims 
@mrbobbytables 
 sorry for the late response somehow it got lost in my notifications, this would be for the production traffic and we will not have a control over how much people would download it.
Currently our binaries are hosted by google cloud but chinnese users do not have access to GCS buckets due to national firewall

**Comment by idvoretskyi** [comment]
@medyagh this is on the CNCF side already, taking care of this.

**Comment by ljinging** [comment]
@medyagh  We have requested $5200 coupon for your Alibaba Cloud Account . You should be able to see it after you log in Alibaba Cloud. It's under alibabacloud.com -> log in -> Expenses -> User Center -> Coupons.

Except for the minikube binaries, we suggest you host the related docker image on Container Registry of Alibaba Cloud (ACR https://www.alibabacloud.com/product/container-registry).  ACR personal edition is free of charge for million developers. We are looking forward to promoting the popularization of K8s together.

**Comment by idvoretskyi** [comment]
@ljinging I'm a bit confused - does the Alibaba Cloud Account exist? We're setting a CNCF-owned, should we cancel this process?

cc @dims

**Comment by dims** [comment]
@medyagh same question as @idvoretskyi , also please grant access to the account for @idvoretskyi if so, as we have CNCF taking care of all accounts.

**Comment by justaugustus** [comment]
@idvoretskyi -- Do we know the current status of this?

**Comment by idvoretskyi** [comment]
@justaugustus pending still, but thanks for flagging.

**Comment by justaugustus** [comment]
@idvoretskyi -- Just wanted to check in on this one!
/assign @justaugustus @idvoretskyi

**Comment by idvoretskyi** [comment]
@justaugustus the work in progress on this under the CNCF credits program, will keep us posted

**Comment by justaugustus** [comment]
> @justaugustus the work in progress on this under the CNCF credits program, will keep us posted

@caniszczyk -- Can we get a commit date on either:

- funding this via Cloud Credits
- directly funding for Alibaba

**Comment by mrbobbytables** [comment]
This issue has been open for going on 2.5 years now. We can bump again with CNCF, but before we do is this something that is still desired?
