### ISSUE TITLE
request: recurring 12,000 USD/month to fund AWS-VMs for integration tests

### ISSUE THREAD

**Issue by prezha** [kubernetes/funding#15]
as [previously discussed](https://github.com/kubernetes/funding/issues/10#issuecomment-635633146) with @medyagh, we are further expanding minikube integration testing setup in AWS cloud under both Windows and Linux OS where we need to use baremetal EC2 instances for nested virtualisation and need your additional support in funding for this next step

here is the link for the estimate: https://calculator.aws/#/estimate?id=0280b446af29dd41f4b85d9eebe77cf39eed8ad6

thanks,
Predrag

**Comment by medyagh** [comment]
I confirm I asked @prezha to help me with starting the process for increase the funding so we can use barmetal instances.
needed for integration test for KVM and Hyperv drivers of minikube.

@prezha would be the point of contact for any questions on the behalf of minikube team.

**Comment by dims** [comment]
@prezha @medyagh are you already using up the current budget?

**Comment by prezha** [comment]
@dims , yes, we've used up current budget already

**Comment by dims** [comment]
@idvoretskyi can you please take a look?

**Comment by idvoretskyi** [comment]
@dims @medyagh this significantly exceeds our currently allocated budget - we ask projects to stay around $3k monthly or less (https://github.com/cncf/servicedesk#how-can-i-use-the-computing-infrastructure-by-cncf).

Any reason why the CNCF bare metal cluster is not an option? See more details here - https://github.com/cncf/cluster.

**Comment by sftim** [comment]
If the main driver is access to virtualization instructions rather than overall throughput, and the CNCF cluster isn't the right fit either, other providers such as [Equinix Metal](https://metal.equinix.com/product/) could prove more cost-effective.

**Comment by idvoretskyi** [comment]
@sftim CNCF Cluster is Equinix Metal (Packet) essentially.

Please see the link I posted above.

**Comment by prezha** [comment]
@idvoretskyi, @sftim thanks for your responses and suggestion
can we please get access to that cluster and test it?

**Comment by idvoretskyi** [comment]
@prezha sure, please proceed as described here - https://github.com/cncf/cluster

**Comment by prezha** [comment]
@idvoretskyi thanks, we've opened a request under https://github.com/cncf/cluster/issues/154

**Comment by idvoretskyi** [comment]
@prezha awesome, thanks, will keep tracking it.

**Comment by prezha** [comment]
@idvoretskyi excellent, many thanks

**Comment by dims** [comment]
Looks like this was taken care of in https://github.com/cncf/cluster/issues/154

thanks,
Dims
