### ISSUE TITLE
request: recurring <$1000USD/month to fund e2e testing on alibabacloud.com, via kOps

### ISSUE THREAD

**Issue by justinsb** [kubernetes/funding#17]
- **Description**: 

kOps has initial support for alibabacloud.com.  In order to enhance this support, and to enhance the stability of kubernetes as a whole by adding another platform under test, we request funding for account(s) to be added to the project-run e2e test runners.  These accounts will initially be used by kOps e2e periodic jobs, but may in future be used by other jobs also.

- **Requesting SIG**: kOps, a subproject of sig-cluster-lifecycle

- **SIG approval**: 

Pending.  (Will follow process as described in  https://github.com/kubernetes/funding#sig-or-committee-approvals )

- **Cost**:  Estimated to be less than $1000 per month, most likely closer to $100 if we average one concurrent e2e run.
  - Frequency: Cloud billing; likely paid monthly
  - Scale function: Cost will be based on number of e2e jobs, their duration, and the number of nodes / size of nodes used.  Generally if we set up only a few periodic jobs we can expect to average about one cluster, depending on frequency of jobs run.

- **SIG approval list archive URL**: TODO ( link to mailing list or github discussion )

- **Owners for renewal**: ??

- **Cancellation criteria**: ??

- **Alternatives considered**: ??

**Comment by dims** [comment]
+1

**Comment by parispittman** [comment]
+1 

service desk ticket with cncf was entered: 742 
cc. @idvoretskyi

**Comment by idvoretskyi** [comment]
@parispittman thanks!

cc @caniszczyk

**Comment by parispittman** [comment]
@caniszczyk can you give folks the info about cloud credits program here?

**Comment by denverdino** [comment]
@justinsb Thanks for the request. Just want to clarify several things, is for Kops only or for other CNCF project testing on Alibaba Cloud?

Our team contributes to Kops for the Alibaba Cloud before, but Kops is not very popular in chinese developer, so we don't continue put more effort on the enhancement and bug fixing. And Kops has deprecated Alibaba Cloud in Feb. https://github.com/kubernetes/kops/pull/10746 So, we hope to have better understanding for which kind of support for Kops should be provided. 

Thanks again.

**Comment by justaugustus** [comment]
> @caniszczyk can you give folks the info about cloud credits program here?

Cloud Native Credits: https://www.cncf.io/credits/

> @justinsb Thanks for the request. Just want to clarify several things, is for Kops only or for other CNCF project testing on Alibaba Cloud?
> 
> Our team contributes to Kops for the Alibaba Cloud before, but Kops is not very popular in chinese developer, so we don't continue put more effort on the enhancement and bug fixing. And Kops has deprecated Alibaba Cloud in Feb. [kubernetes/kops#10746](https://github.com/kubernetes/kops/pull/10746) So, we hope to have better understanding for which kind of support for Kops should be provided.

@kubernetes/kops-maintainers -- Given the deprecation, is this funding request still relevant?

**Comment by johngmyers** [comment]
I was planning on ripping out the Alibaba code soon after kOps branches for 1.23, so I would say this request is no longer relevant.

**Comment by justaugustus** [comment]
@johngmyers -- Thanks for the update!
/close
