### ISSUE TITLE
request: US$5K for the year to fund CAPG development

### ISSUE THREAD

**Issue by cpanato** [kubernetes/funding#18]
- **Description**: 

I help to maintain the [cluster-api-provider-gcp](https://github.com/kubernetes-sigs/cluster-api-provider-gcp) and to implement/fix or improve the project I use my personal account to test the changes or/and use CI other times, which is slow and if I need to try something different I cannot (or need to hack the scripts, which is not good)

I don't have any company supporting those costs and time, I do everything in my "free" time. 
I don't contribute more because it can cost some money from my pocket and last month I've spent around 40 dollars on GCP. I know it's not much but for a personal thing, it is and can impact my personal budget.

So I would like to request some credits to run the development for CAPG on GCP. I'm not requesting any kind of payment or anything else for the time I spend on that. It is only for run the workloads on GCP.

Thanks so much in advance.

Update based on (https://github.com/kubernetes/funding/issues/18#issuecomment-830020360): LFX Interns can use this as well

- **Requesting SIG**:
Cluster Lifecycle / Cluster-api

- **SIG approval**: 

- **Cost**:
US$5K for the year

- **Alternatives considered**:
Recurring expenses?

/cc @fabriziopandini @dims @neolit123

**Comment by fabriziopandini** [comment]
+1 @cpanato work on CAPG is super valuable and it could contribute to make our release signal more stable, let's help him if possible

**Comment by dims** [comment]
+1 from me. 

@cpanato as we on board some other folks (say LFX interns) we may need a bit more? Let's bump this to $5k. 

Steering Folx, This would basically come out of the existing infra maintained by wg-k8s-infra, So we don't really need to involve CNCF service desk. We would basically mint a new GCP project for the folks working on CAPG and monitor the usage.

**Comment by cpanato** [comment]
sounds good to me, then we can share the account, agree, updated the Issue to reflect this

**Comment by neolit123** [comment]
I appreciate your efforts @cpanato 

Frankly, I think we should just drop the CAPG CI signal and other work at this point and leave it to rot until companies recognize its importance and start funding its development.

But given you and others here are in favour, I find it diffucult to object.

Can we fund one year as a start and see how it goes?

**Comment by cpanato** [comment]
the idea is not for CI signal, but is to develop and fix issues in CAPG

**Comment by spiffxp** [comment]
Non-binding +1 as a wg-k8s-infra lead.  We're still in very early days in terms of allocating budgets to one-off projects, but I'm supportive of the idea of carving out some portion of k8s-infra budget for actively involved contributors (which @cpanato very much is)

Other examples would be: giving ci signal folks compute budget to run queries against bigquery, giving node ci signal folks budget for node repro, etc.  Not quite ready to open the floodgates, but if people are interested in that, come chat with us in #wg-k8s-infra.

That said, I am firmly in the camp that it's steering's call how we spend the k8s-infra budget, and I'm trusting @dims to escalate as needed.

**Comment by dims** [comment]
+1 wearing my steering hat (as well as wg-k8s-infra)

**Comment by cpanato** [comment]
There is anything that I need to do to move forward with this request? thanks!

/remove-lifecycle stale

**Comment by fabriziopandini** [comment]
I can't help in pushing this forward, but I can give all my support and another big +1 to this request

**Comment by neolit123** [comment]
Funding is owned by the k8s steering. You can email them or post in their
slack to let them know. I have not seen discussions about this topic
outside of this thread, but might have missed it.

**Comment by neolit123** [comment]
added comment on slack:
https://kubernetes.slack.com/archives/CPNFRNLTS/p1628174228007900

**Comment by mrbobbytables** [comment]
+1 with my steering 🎩 on.

**Comment by cblecker** [comment]
+1. Easy thing to fund.

@spiffxp @ameukam: Non-blocking question.. how does usage get tracked from the k8s infra standpoint right now? Are we just looking at spending graphs and estimating? Is there ways to set up enforceable budgets?

**Comment by ameukam** [comment]
> how does usage get tracked from the k8s infra standpoint right now? Are we just looking at spending graphs and estimating? 

We currently track resources consumption and GCP services usage through Google Datastudio dashboards. AFAIK, only members of kubernetes-wg-k8s-infra@googlegroups.com can access those dashboards. Link of the dashboard : https://datastudio.google.com/reporting/14UWSuqD5ef9E4LnsCD9uJWTPv8MHOA3e/page/tPVn. 
Some changes and improvements need to be done in order to make it accessible to the community. 
https://github.com/kubernetes/k8s.io/issues/1625
https://github.com/kubernetes/k8s.io/issues/1590

Budget spending covers only GCP.

> Is there ways to set up enforceable budgets?

It's possible to enforce [budgets] on GCP projects. We plan to define policies and budgets enforcement during v1.24: https://github.com/kubernetes/k8s.io/issues/1375. 

[budgets]: https://cloud.google.com/billing/docs/how-to/budgets.

**Comment by derekwaynecarr** [comment]
+1

**Comment by liggitt** [comment]
+1

**Comment by spiffxp** [comment]
I think where were stuck right now is implementing and enforcing a budget but should be doable soonish. Does someone want to come discuss at the next wg k8s infra meeting?

**Comment by justaugustus** [comment]
+1 with my Steering hat on.

> I think where were stuck right now is implementing and enforcing a budget but should be doable soonish. Does someone want to come discuss at the next wg k8s infra meeting?

@kubernetes/sig-k8s-infra-leads -- what's the latest on this one?

**Comment by ameukam** [comment]
> +1 with my Steering hat on.
> 
> > I think where were stuck right now is implementing and enforcing a budget but should be doable soonish. Does someone want to come discuss at the next wg k8s infra meeting?
> 
> @kubernetes/sig-k8s-infra-leads -- what's the latest on this one?

We can close it. Project have been created with budget requested. PRs related are linked in this issue.

**Comment by cpanato** [comment]
yes, we can close, we are also using the project with the LFX mentees 
thanks for all!

/close

**Comment by justaugustus** [comment]
Thanks everyone!
Linking the relevant PRs:
- https://github.com/kubernetes/k8s.io/pull/2904
- https://github.com/kubernetes/k8s.io/pull/2908
- https://github.com/kubernetes/k8s.io/pull/2940
