### ISSUE TITLE
request: recurring $39/month to fund streamyard account

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/funding#19]
- **Description**: An annual subscription to [Streamyard](https://streamyard.com/). Streamyard is a browser based live streaming studio. It removes all the hardware/software requirements for streaming and has native integration with YouTube/Twitch etc. It will be used for streaming community events such as [Meet Our Contributors](https://www.kubernetes.dev/events/meet-our-contributors/), the [monthly Community Meeting](https://www.kubernetes.dev/events/community-meeting/), and other contributor events such as the [Contributor Celebration](http://k8s.dev/celebration).
- **Requesting SIG**: SIG Contributor Experience
- **Cost**: $39/mo | $468/year (if monthly billing is preferred, it's $49/mo | $588/year)
  - Frequency: Annual
  - Scale function: None
- **Owners for renewal**: SIG ContribEx
- **Cancellation criteria**: A better/cheaper alternative tool is available or we no longer stream events
- **Alternatives considered**: 
  - We have used OBS and relied on individuals to stream in the past; however this has relied on a very small subset of people that have additional hardware and elevated access to YouTube to stream events. There have been multiple instances where we have not been able to stream events in the past because no one is available. 
  - Zoom also has native streaming capabilities, but it puts a large logo in the bottom right and would require people have elevated access within YouTube itself.

cc @jberkus @parispittman @alisondy

**Comment by dims** [comment]
+1 from me!

**Comment by nikhita** [comment]
+1 as well :)

**Comment by cblecker** [comment]
+1

**Comment by liggitt** [comment]
+1

**Comment by jberkus** [comment]
+1 non-binding from me.

My ability to host MOC and Office Hours depends on this, because OBS has such finicky requirements.

**Comment by mrbobbytables** [comment]
FYI - streamyard is going to launch a group/org accounts soon. I've reached out for more information.

**Comment by mrbobbytables** [comment]
The pricing for a team account was not worth it for our needs, I've created a team stream-team@kubernetes.io who will be the owner for the streamyard account, at this point a CNCF member will need to login and add the billing information.

**Comment by mrbobbytables** [comment]
The service desk ticket is: CNCFSD-816

**Comment by mrbobbytables** [comment]
This was completed 👍 
/close
