### ISSUE TITLE
request: one-time $450USD to fund New Contributor Workshop

### ISSUE THREAD

**Issue by nikhita** [kubernetes/funding#20]
-  **Description**
@palnabarun, @divya-mohan0209 and I are organizing a [Kubernetes New Contributor Workshop](https://www.instamojo.com/cloudyuga/kubernetes-contributors-workshop/) at Kubernetes Community Days (KCD) Bangalore on 24 June 2021. We expect ~150 people to join the virtual workshop.
We would like to request 30 CNCF store coupon codes for [straight](https://store.cncf.io/products/kubernetes-mens-short-sleeve-concert-tee)/[fitted](https://store.cncf.io/products/the-kubernetes-ladies-kollaborator-short-sleeve-concert-tee) tshirts to distribute to first 30 attendees who have their PR merged on the [contributor-playground](https://github.com/kubernetes-sigs/contributor-playground/) repo.
As per the [NCW instructions](https://github.com/kubernetes/community/blob/master/mentoring/programs/new-contributor-workshop/resources/new-contributor-workshop-lead.md#coupon-codes), requesting for coupon codes involves creating a Service Desk ticket.
If there any remaining unused coupon codes after the event (very unlikely!), we will merge them with the existing coupon codes pool that contribex owns.
For context, in the [previous version](https://github.com/kubernetes-sigs/contributor-playground/tree/master/india/k8s-blr-2021) of the NCW that we had organized in the k8s Bangalore meetup, we had ~100 attendees and had [36 people](https://github.com/kubernetes-sigs/contributor-playground/tree/master/india/k8s-blr-2021/workdir) successfully merge a PR.

- **Requesting SIG**: SIG Contributor Experience
- **SIG approval**: I am a Technical Lead for contribex, also cc'ing @mrbobbytables (chair) for approval below
- **Cost**:
Each straight/fitted tee costs $15.
For 30 tees, total cost = $15 x 30 = $450

/assign @dims 
steering committee + involved with KCD Bangalore

/assign @mrbobbytables 
steering committee + contribex chair

/assign
I will create a Service Desk ticket once this gets lgtm from at least two SC members.

**Comment by mrbobbytables** [comment]
+1 from me 👍

**Comment by dims** [comment]
+1

**Comment by nikhita** [comment]
Service desk ticket created - https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-826

I will close this issue once the service desk ticket is resolved.

**Comment by nikhita** [comment]
We have the codes. Closing!
