### ISSUE TITLE
request: one-time $1 200 USD to fund Cloud Native / Open source swag for Tauranga Careers show

### ISSUE THREAD

**Issue by riaankleinhans** [kubernetes/funding#21]
- **Description**: 
30 July 2021 the [ii team](ii.coop)  would do an exhibition at the [Tauranga Careers show](https://www.canvascareers.co.nz/), New Zealand. 
We will be showing off all things "Open source" and "Cloud native" to get the young people of NZ interested to join our community.
It would be great to give away some swag to the kids we have conversations with.
- **Requesting SIG**: SIG Contributor Experience
- **SIG approval**:https://kubernetes.slack.com/archives/C1TU9EB9S/p1625574380308100
- **Cost**:
    - [Kubernetes Decal](https://store.cncf.io/products/kubernetes-decal) $0.50 x 1500 @ $750 USD
    - [The Fitted Kubernetes Short Sleeve Concert Tee](https://store.cncf.io/products/the-kubernetes-ladies-kollaborator-short-sleeve-concert-tee) $15.00 x 30 @ $450 USD
    - $1 200 USD + Shipping to NZ.

/assign @mrbobbytables @nikhita @idvoretskyi

**Comment by idvoretskyi** [comment]
This is sorted out internally at CNCF.

/close
