### ISSUE TITLE
request: one-time 10 t-shirt codes to fund Usability study thank yous

### ISSUE THREAD

**Issue by tashimi** [kubernetes/funding#22]
- **Description**: 
- **Requesting SIG**: Usability
- **SIG approval**: Yes
- **Cost**: n/a
- **Alternatives considered**: n/a 

Hi! We at SIG-Usability have been giving Kubernetes t-shirts to users of Kubernetes who take an hour to do an in-depth usability study with us (we have presented on this at serveral Kubecons and plan to do an in-depth dive into what we're learning at KubeCon NA). We have run out of t-shirt codes, and we have 10 people we've interviewed already that we owe t-shirts too. Could you please connect us with more t-shirt codes?

Thanks, Tasha

**Comment by dims** [comment]
+1 from me!

@nikhita do you want to open the servicedesk request for this please?

**Comment by nikhita** [comment]
Created the sevice desk ticket - `CNCFSD-866`

@tashimi I'll let you know once I hear back form CNCF.

**Comment by nikhita** [comment]
@tashimi just shared the coupon codes with you on slack.

Closing!
