### ISSUE TITLE
request: one-time $225USD to fund New Contributor Workshop

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/funding#24]
- **Description**: 
@rajaskakodkar, @RinkiyaKeDad and I organized a Kubernetes New Contributor Workshop at [HackIllinois Open Source Fellowship](https://fellowship.hackillinois.org/) on 1st October 2021. There were about 50 participants to join the virtual workshop.
We would like to request 15 CNCF store coupon codes for straight/fitted t-shirts to distribute to first 15 attendees who have their PR merged on the [contributor-playground](https://github.com/kubernetes-sigs/contributor-playground/tree/master/remote/hackillinois-osf-2021) repo.
If there any remaining unused coupon codes after the event (very unlikely!), we will merge them with the existing coupon codes pool that contribex owns.

- **Requesting SIG**:
SIG-Contributor Experience
- **SIG approval**: 
- **Cost**: Each straight/fitted tee costs $15. For 15 tees, total cost = $15 x 15 = $225

/assign @nikhita @mrbobbytables @dims 
/assign
Will create a service desk ticket after this gets approved!

**Comment by MadhavJivrajani** [comment]
Wow, cannot math, oops!

**Comment by nikhita** [comment]
I'm ok with this but would also like a +1 from @mrbobbytables

**Comment by mrbobbytables** [comment]
I'm fine with it, we don't have enough codes in our current allotment so definitely need to do a request.

**Comment by MadhavJivrajani** [comment]
Thanks all! ❤️ 
I will create a help desk ticket :)

**Comment by nikhita** [comment]
@MadhavJivrajani only contribex chairs or steering members have access to the help desk. I have created a ticket `CNCFSD-959` (for those who have access). Will share an update once I hear from CNCF.

**Comment by MadhavJivrajani** [comment]
Ah I see!
Thanks so much :D

**Comment by nikhita** [comment]
@MadhavJivrajani @RinkiyaKeDad @rajaskakodkar I have shared the codes with you privately.

The coupon codes should work for any product in the CNCF store afaik, the straight/fitted shirts seem to be out of stock right now.

Closing this issue as done. Please reach out if you need any additional help.
