### ISSUE TITLE
request: recurring $50/month to fund experimental project for container distribution

### ISSUE THREAD

**Issue by ameukam** [kubernetes/funding#28]
- **Description**: 
SIG k8s Infra is currently looking at options that will help reduce the cost burden of container distribution. We want to test 2 approaches:
  - synchronize blobs of the Kubernetes container images to a AWS S3 bucket and make them available to AWS customers
  - distribute container images using a [Lambda function](https://aws.amazon.com/lambda/edge/). The lambda function will act as a proxy in front of k8s.gcr.io.
  A funded AWS account is needed to do some tests.
- **Requesting SIG**: sig-k8s-infra
- **Cost**:
  - Frequency: monthly
  - Scale function: 
     cost increase is not expected here. It could be the result of hidden costs associated with usage AWS services.
- **SIG approval list archive URL**: https://github.com/kubernetes/k8s.io/issues/1834
- **Owners for renewal**: sig-k8s-infra
- **Cancellation criteria**: Unable to properly distribute Kubernetes container images from k8s.gcr.io

**Comment by ameukam** [comment]
/sig k8s-infra
cc @dims

**Comment by dims** [comment]
+1 from me.

**Comment by parispittman** [comment]
+1

**Comment by hh** [comment]
As a test of the Cloud Credits pipeline can someone from steering make a request for this $50 via CNCF.io/credits?

**Comment by mrbobbytables** [comment]
+1

**Comment by dims** [comment]
@hh CNCFSD-1060 is the service desk request.

**Comment by justaugustus** [comment]
+1 for Steering + @kubernetes/release-engineering!

**Comment by idvoretskyi** [comment]
@ameukam +1 from the credits side of the house, do you need any assistance with setting the account up?

**Comment by ameukam** [comment]
> @ameukam +1 from the credits side of the house, do you need any assistance with setting the account up?

@idvoretskyi I can set up an account and give you the account id for Org invitation or give you an e-mail address. WDYT ?

**Comment by idvoretskyi** [comment]
I think @hh will take case of everything needed here.

**Comment by cpanato** [comment]
+1

**Comment by hh** [comment]
The creation of the google group, to grant access to the account / OU is here:
https://github.com/kubernetes/k8s.io/pull/3301

**Comment by dims** [comment]
thanks for the update @hh

**Comment by ameukam** [comment]
The account is created and I confirm we have access to it. 

/close
