### ISSUE TITLE
request: one-time $190USD to fund designing logo for Node Feature Discovery 

### ISSUE THREAD

**Issue by marquiz** [kubernetes/funding#3]
I'd like to request help from @alexcontini in designing a logo for the [Node Feature Discovery](https://github.com/kubernetes-sigs/node-feature-discovery) (NFD) project (see kubernetes-sigs/node-feature-discovery#255). Similar to what she did for [kubeadm](https://github.com/kubernetes/kubeadm/issues/1588).

I discussed with @dankohn and he estimated the cost at $190.

This topic hasn't been discussed in SIG Node, yet. I'll update this issue wrt. that later.

- **Description**: Help designing logo for [Node Feature Discovery](https://github.com/kubernetes-sigs/node-feature-discovery)
- **Requesting SIG**: SIG Node
- **SIG approval**: *n/a*
- **Cost**: Estimated $190

**Comment by philips** [comment]
We discussed this on the Steering call today. The initial reaction from the Steering committee was hesitation for two reasons:

1. What sort of precedent this would be setting for the dozens (hundreds?) of sub projects in the Kubernetes project? Would it be helpful to Kubernetes if all of those projects had a visual representation? How?

2. There is prior art for projects inside of Kubernetes having logos including kops, kubeadm, kubectl, minikube and a common theme across these projects are end user facing. So, perhaps we should create a guideline that a project should be user facing with a significant user base where a graphical representation for the project might be helpful for docs, presentations, etc.

**Potential alternatives to consider:**
- Logos for SIGs to use on their projects as a set of common iconography around projects

cc steering members in the discussion @bgrant0607 @smarterclayton @sarahnovotny

**Comment by philips** [comment]
Also, thanks for being the first person to exercise the Kubernetes funding process!

**Comment by marquiz** [comment]
Thanks for your thoughtful response! I had mostly thought this from the point of view of this one project. In a wider context what you said makes totally sense.

I think the "potential alternative", i.e. per-SIG logos for the projects to use would be useful.

**Comment by jberkus** [comment]
@philips hey, dug into this, and apparently NFD *does* have UI, and they request for the logo was in order to have an icon for that. So the criterion for "end user facing" may be met.

**Comment by philips** [comment]
@marquiz How would you like to proceed? I am happy to bring this up at the next steering committee meeting if you feel there is an end user value to having a logo. It would be helpful if you could provide a reference to a screecast or something showing the project that the logo would be used in.

**Comment by dims** [comment]
/close

please reopen if still needed. happy to review this again as @philips mentioned.
