### ISSUE TITLE
CNCF MacOS Developer Account for Signing Release Binaries

### ISSUE THREAD

**Issue by klaases** [kubernetes/funding#30]
### Organization or Repo

kubernetes/minikube

### User affected

MacOS users

### Describe the issue

Hi, the [minikube](https://minikube.sigs.k8s.io/docs/) team would like to sign release binaries for MacOS.

Could CNCF please supply us with an [Apple developer account](https://developer.apple.com/support/compare-memberships/), or perhaps cover the annual fees?

Apple provides a [few waiver](https://developer.apple.com/support/membership-fee-waiver/) for non-profits. However, minikube operates within CNCF and does not have its own non-profit entity.

**Comment by dims** [comment]
+1

**Comment by dims** [comment]
cc @justaugustus

**Comment by klaases** [comment]
When users try to run minikube, and the coming minikube GUI, they are discouraged from continuing due to lack of security.

Specifically, Apple mentions that they cannot confirm whether minikube contains malware. By signing, we hope to provide a more secure user experience on Mac OS!

![minikube-security](https://user-images.githubusercontent.com/93291761/164092082-d2245ece-29d4-49a9-bf0d-e20e4a7eece3.png)

**Comment by tpepper** [comment]
+1

**Comment by parispittman** [comment]
+1

**Comment by klaases** [comment]
Hi @[justaugustus](https://github.com/justaugustus), have their been any updates with regards to being able to sign the minikube release binaries?

**Comment by klaases** [comment]
Hi, please remove the "lifecycle/rotten" label as we are still looking to sign the minikube binaries.

@justaugustus is there anything we can do to help speed up the process?

**Comment by klaases** [comment]
Friendly follow-up, would the minikube project be able to obtain funding or access to an Apple developer account for the purposes of signing the minikube release binary?

Here are the last two releases that we would like to be able to sign for the security of our users:
- https://github.com/kubernetes/minikube/pull/14955
- https://github.com/kubernetes/minikube/pull/14707
