### ISSUE TITLE
request: recurring $120USD/year to fund Contributor Comms collaboration and messaging tool 

### ISSUE THREAD

**Issue by chris-short** [kubernetes/funding#32]
- **Description**: Contributor Comms is requesting a Buffer account to help schedule and more effective 
- **Requesting SIG**: SIG-ContribEx
- **SIG approval**: 
- **Cost**: $120/year
  - Frequency: Annually
  - Scale function: Going past a certain number of team members on Buffer may incur additional costs. The intent is tightly managing those that can schedule on behalf of K8sContributors.
- **SIG approval list archive URL**: Multiple Slacks, ContribEx and Contributor-Comms meetings
- **Owners for renewal**: Bob Killen, Kaslin Fields, and/or Chris Short
- **Cancellation criteria**: If team moves to alternative tooling at some point, we'll be sure to open an issue.
- **Alternatives considered**: HootSuite (expensive for what you get), TweetDeck (lacks ability to cap number of tweets per day or setting up more advanced scheduling), Canva (it can schedule but it lacks features similar to TweetDeck)

**Comment by chris-short** [comment]
/assign @mrbobbytables 

I know you're busy but, here's the request.

**Comment by mrbobbytables** [comment]
+1 its not expensive and a reasonable ask + make the scheduling of tweets dramatically easier.

**Comment by dims** [comment]
+1 from me

**Comment by justaugustus** [comment]
+1 to fund.

> SIG approval list archive URL: Multiple Slacks, ContribEx and Contributor-Comms meetings

@chris-short -- can you link at least one of the approval threads (preferably a GH issue or mailing list thread)?

I'm sure this is already approved from the @kubernetes/sig-contributor-experience-leads side, but we should leave some breadcrumbs here for any future archaeology.

**Comment by jberkus** [comment]
Contributor Comms really needs this tool.  Please approve, thanks!

I'm co-approving as ContribEx Co-chair.

**Comment by parispittman** [comment]
+1 - I wanted this tool when we created the group so its long overdue

**Comment by liggitt** [comment]
+1

**Comment by Atharva-Shinde** [comment]
+1 we really need this

**Comment by mrbobbytables** [comment]
Request has been submitted, here is the ticket ID: CNCFSD-1319

**Comment by cblecker** [comment]
CNCF has completed request.
