### ISSUE TITLE
request: recurring $5USD/month to fund replacement slack inviter

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/funding#33]
- **Description**:  The [slackin service](https://github.com/kubernetes-sigs/slack-infra/tree/main/slackin) that we currently use to send invites for slack.k8s.io is down due to using a now deprecated API.  With no current maintainers, and in an effort to run less of this type of infrastructure,  we would like to use [Community Inviter Slack App](https://communityinviter.com/) as an alternative. There is a free ad-supported version, but we would prefer to use the ad-free version with our own branding.
- **Requesting SIG**: SIG Contributor Experience
- **Cost**: $5
  - Frequency: monthly
  - Scale function: Mpme
- **Owners for renewal**: CNCF / SIG ContribEx
- **Cancellation criteria**: A better/cheaper alternative or someone takes interest in maintaining the slackin fork.
- **Alternatives considered**: Our fork of slackin, not many other options are available that fill this particular niche. There are other options out that that rely on sending out an email with a premade slack invite link, but those are limited to a certain # of users and would require refreshing every so often. With a community our size and its growth that would add more friction for the slack admins.

/cc @jberkus @BenTheElder  @markyjackson-taulia @dims @palnabarun @ameukam

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/community/issues/6813

**Comment by dims** [comment]
+1 from me

**Comment by cblecker** [comment]
+1 from me as well

**Comment by justaugustus** [comment]
+1!

**Comment by ameukam** [comment]
+1

**Comment by jberkus** [comment]
+1, both as SIG-Contribex and as one of the Slack admins.

**Comment by markjacksonfishing** [comment]
+1 as part of sig-contribex and a slack admin

**Comment by BenTheElder** [comment]
What happened to this?

**Comment by dims** [comment]
Already Done. we can close this now.

**Comment by BenTheElder** [comment]
Thanks dims!
