### ISSUE TITLE
request: recurring $9USD/month to fund LWKD newsletter distribution

### ISSUE THREAD

**Issue by jberkus** [kubernetes/funding#35]
- **Description**: $9/month to pay for Buttondown newsletter distribution for [Last Week in Kubernetes Development](https://lwkd.info)
- **Requesting SIG**: ContribEx
- **SIG approval**: https://github.com/kubernetes/community/issues/6930
- **Cost**: 9
  - Frequency: monthly
  - Scale function: Not expected to increase
- **SIG approval list archive URL**: [approval issue](https://github.com/kubernetes/community/issues/6930)
- **Owners for renewal**: SIG-ContribEx chairs & TLs
- **Cancellation criteria**: Increase in rates, LWKD ceases publishing, or CNCF supports an official newsletter service
- **Alternatives considered**: see discussion in https://github.com/kubernetes/community/issues/6930

Note: CNCF has already cleared paying for this, so the SC just needs to approve it.

**Comment by jberkus** [comment]
@kubernetes/steering-committee approval, please?

**Comment by mrbobbytables** [comment]
lgtm with steering hat on

**Comment by justaugustus** [comment]
+1 (Steering)

**Comment by BenTheElder** [comment]
LGTM
+1 (Steering)

**Comment by tpepper** [comment]
This seems reasonable/useful to me.  +1 (Steering)

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
@cblecker @cpanato @palnabarun

**Comment by cblecker** [comment]
LGTM

**Comment by BenTheElder** [comment]
Marking approved as we have 5/7 steering members's +1 now.

**Comment by cpanato** [comment]
+1

**Comment by BenTheElder** [comment]
@jberkus nudge

**Comment by jberkus** [comment]
/close

This was paid a year ago, oops.
