### ISSUE TITLE
CNCF Swag Codes for Kubernetes Contributors

### ISSUE THREAD

**Issue by nikhita** [kubernetes/funding#37]
- **Description**:

SIG Contribex has had a list of swag codes that we award to (new) contributors who are doing good work. We've also shared these codes with k8s maintainers who want to send swag to new contributors they are working with. It's been great to keep folks encouraged and motivated!

The existing codes were generated around 2017 and are no longer valid. Only the codes for the Kubernetes Hoodie are valid.

We'd like to have more codes for tshirts, bottles and socks.

- **Requesting SIG**: SIG Contributor Experience
- **SIG approval**: @mrbobbytables @jberkus can either of you approve with your contribex chair hat?
- **Cost**:
Not sure, but maybe 10 of each `tshirt | bottle | socks` swag codes?

The list of swag codes need to be shared with `kubernetes-sig-contribex-leads@googlegroups.com`.

/assign @mrbobbytables @jberkus

**Comment by cpanato** [comment]
+1

**Comment by tokt** [comment]
+1 and thank you!

**Comment by jberkus** [comment]
Hmmm.  I have no idea if this needs to go through steering/funding.  I think next step is to ask the staff.

**Comment by nikhita** [comment]
It looks like I don't have access to CNCF Service Desk anymore. @jberkus @mrbobbytables can either of you please create a request on service desk for this? Thanks!

**Comment by nikhita** [comment]
Also, the list of swag codes need to be shared with `kubernetes-sig-contribex-leads@googlegroups.com`

**Comment by jberkus** [comment]
Reached out directly.

**Comment by nikhita** [comment]
@jberkus thanks for the help in restoring my service desk access 💛 

Created a service desk ticket - CNCFSD-1574

**Comment by nikhita** [comment]
Received 15 discount codes from CNCF and have added it to the spreadsheet that contribex leads have access to. Closing.
