### ISSUE TITLE
request: US$5K for the year to fund CAPA development

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes/funding#38]
**Description**:
I am a maintainer of [cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws) and to implement/fix or improve the project I use my official account to test the changes or/and use CI other times.

We have LFX intern in CAPA project this year who is a student and would need an AWS account to make the [CAPA LFX project](https://mentorship.lfx.linuxfoundation.org/project/2d76dbe6-43eb-465e-a852-64b2e48f2c68) possible.

So I would like to request some credits to run the development for CAPA on AWS. I'm not requesting any kind of payment or anything else for the time I spend on that. It is only for running the workloads on AWS.

Thanks so much in advance.

**Requesting SIG**:
Cluster Lifecycle / Cluster-api

**SIG approval**:

**Cost**:
US$5K for the year

**Alternatives considered**:
@richardcase is trying to get AWS credits for his personal account but the TAT for the response 
from AWS is 30days, we cannot afford that much time since the mentorship for this term has already started.

/cc @richardcase

**Comment by mrbobbytables** [comment]
I would ping sig-k8s-infra, we have a large amount of aws credits that they have access to.

**Comment by Ankitasw** [comment]
> I would ping sig-k8s-infra, we have a large amount of aws credits that they have access to.

cc @dims if you know about this?

**Comment by dims** [comment]
@mrbobbytables we'll need steering to approve :)

similar to what we did before in:
- https://github.com/kubernetes/k8s.io/pull/2904
- https://github.com/kubernetes/funding/issues/18

**Comment by palnabarun** [comment]
+1 with my steering 🎩 .

We have a lot of credits that we can use now. The requested amount is a small chunk of what we have access to. I would let sig-k8s-infra decide on the mechanics to put a budget limit similar to how it was done in https://github.com/kubernetes/k8s.io/pull/2940.

**Comment by dims** [comment]
@hh Can you please help with this when the majority of the steering has approved it?

We'll need a temporary account with some budget restrictions (not attached to a specific person) that lfx mentee can use for the duration of their work.

**Comment by justaugustus** [comment]
+1 from Steering!

**Comment by cpanato** [comment]
Off steering hat:
We from CAPG requested a similar amount for CAPG development and to be used in the LFX mentorship program and it is working great so far.

with steering hat:
+1

**Comment by tpepper** [comment]
+1 from steering hat wearer

**Comment by mrbobbytables** [comment]
lgtm with steering hat on

**Comment by BenTheElder** [comment]
+1 steering

**Comment by Atharva-Shinde** [comment]
Thank you all <3

**Comment by richardcase** [comment]
@Ankitasw - as we have the account to use, guessing we can probably close this issue now?

**Comment by Ankitasw** [comment]
yes, closing this. Thanks for reminder @richardcase
