### ISSUE TITLE
request: increase to recurring $15USD/month to fund buttondown for LWKD

### ISSUE THREAD

**Issue by jberkus** [kubernetes/funding#39]
- **Description**: LWKD needs to increase its buttondown subscription
- **Requesting SIG**: ContribEx
- **SIG approval**: Not requested because this is an increment
- **Cost**: 150
  - Frequency: Annually
  - Scale function: Will increase to $400 if we exceed 5000 subscribers (unlikely)
- **SIG approval list archive URL**: Not requested because this is an increment
- **Owners for renewal**: @jberkus/CNCF projects staff
- **Cancellation criteria**: Developing an alternative and/or stopping LWKD
- **Alternatives considered**: N/A, this is an increment

LWKD has exceeded the subscriber threshold for our current Buttondown tier, approved in #35.  We can't publish to email newsletter until we increase the tier.  The next tier is $12.50/month, which is an increase of $3.50/month.  We are unlikely to ever get to the tier beyond that.

**Comment by BenTheElder** [comment]
LGTM with my steering hat on :-)

Thanks for working on this.

**Comment by mrbobbytables** [comment]
lgtm 👍

**Comment by palnabarun** [comment]
LGTM from my side as well.

**Comment by cpanato** [comment]
Lgtm +1

**Comment by cblecker** [comment]
+1

**Comment by jberkus** [comment]
Great, opening a ticket with CNCF.

**Comment by tpepper** [comment]
+1

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
I believe this was handled?
/assign @mrbobbytables

**Comment by mrbobbytables** [comment]
verified this has been taken care of

/close
