### ISSUE TITLE
EKS clusters for scale testing of windows-service-proxy and operational readiness

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/funding#40]
### Problem Statement

We are in the process of hardening the overall windows on kubernetes experience, and begin paving the road to reduce in-tree tech debt, around things like [possibly simplify kube-proxy](https://github.com/kubernetes/enhancements/pull/3824/files#r1246605611), and also make the [windows support matrix in K8s explicit](https://github.com/kubernetes-sigs/windows-operational-readiness/).

To do this, we'll need to have more infrastructure for customized experiments in the windows server area, and do CI jobs which swap out the in-tree proxy for new approaches which we think will reduce tech debt in-tree, over time, while increasing the K8s experience overall for enterprises.

- So, we will start automating / running some experiments against EKS for along these lines.  - We'd also like this on Azure if possible, but haven't been able to get such resources yet.

We think AWS is a solid foundation as one of the more popular infrastructures that people will.

### Proposed Solution

Let's get started with EKS for operational readiness verification on windows.  This will also help us work through issues such as https://github.com/kubernetes/kubernetes/issues/119022, which we think has specific consequences for AWS and other public clouds, as we discovered recently using our own, internal EKS accounts.

### Cost

We can accomplish our current needs in 5K per month, assuming 2  ~ 3 full time, small clusters of EKS nodes (< 3 each).  We expect this to be "high" bc windows machines/licence node costs are a little higher then normal nodes...

### Open Questions
- [ ] Open
- [ ] Questions

### Next Steps
- [ ] Next
- [ ] Steps

### Other Considerations, Notes, or References
- [ ] Fixes # 
- [ ] xref #

**Comment by jayunit100** [comment]
cc @kubernetes/steering-committee @dims

**Comment by jayunit100** [comment]
cc @aroradaman

**Comment by jayunit100** [comment]
cc @marosset @jsturtevant @aravindhp @claudiubelu

**Comment by BenTheElder** [comment]
If you're just running CI jobs on AWS, we already have resources for this? This is a question for k8s-infra leads.

**Comment by ameukam** [comment]
> If you're just running CI jobs on AWS, we already have resources for this? This is a question for k8s-infra leads.

I think the idea here is to provide an AWS account used by windows-service-proxy maintainers to setup a dev environment and later automate things with the k8s CI.

**Comment by BenTheElder** [comment]
> I think the idea here is to provide an AWS account used by windows-service-proxy maintainers to setup a dev environment and later automate things with the k8s CI.

Got it.

I think the TLDR of the steering meeting is we should be handling this with k8s infra resources first and we should escalate to a funding issue when k8s infra is unsure of or lacks the resources.

E.G. For azure in the future we don't have resources in k8s infra / owned by the project to provide currently.
For AWS we do and k8s infra can handle this request, but probably needs to follow up with a policy for dev accounts long term.

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
/close
This was/will be handled through k8s infra.
