### ISSUE TITLE
DigitalOcean account for E2E testing

### ISSUE THREAD

**Issue by cblecker** [kubernetes/funding#9]
### Problem Statement
@xmudrii on behalf of the github.com/kubernetes-sigs/cluster-api-provider-digitalocean maintainers has requested a DigitalOcean account for assistance with e2e testing:
https://groups.google.com/a/kubernetes.io/d/msg/steering/2O7e8z6m-VY/q1mppiM-BAAJ

### Proposed Solution
Before we request CNCF funding for this, I'd like to ask the CNCF to connect with DigitalOcean (a CNCF member) and see if we can get cloud credits for this, in the same way we have for Google Cloud and AWS.

### Cost
Hopefully no direct cost, if cloud credits are available

### Next Steps
- [ ] Confirm with Steering as to this action, and create ServiceDesk ticket to request accounts

### Other Considerations, Notes, or References
- https://groups.google.com/a/kubernetes.io/d/msg/steering/2O7e8z6m-VY/q1mppiM-BAAJ

**Comment by dims** [comment]
Created a Service Desk ticket - https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-417

**Comment by nikhita** [comment]
Update from service desk ticket - we'll hear more from CNCF about this by EOW.

**Comment by caniszczyk** [comment]
@dims I had a meeting with DO and they are good to go in supplying credits at $1000/month to start! I need to work with the folks who need access to the DO account, need their respective emails to give them access so they can enable the tests

**Comment by dims** [comment]
@caniszczyk Ack. Will request @xmudrii to send you a note with the list of emails.

**Comment by dims** [comment]
Thanks a ton @caniszczyk !!!

**Comment by xmudrii** [comment]
Thanks a lot for the help! This is going to help us a lot and we appreciate it!

@caniszczyk I'll gather the email addresses and will follow up with you tomorrow.

**Comment by cblecker** [comment]
@xmudrii @dims Can we also ensure someone from sig-cloud-provider's leadership is involved and we track who has access to the accounts?

**Comment by dims** [comment]
+1 @cblecker 

@andrewsykim @cheftako WDYT?

**Comment by cheftako** [comment]
Added our sig to the issue. Please keep us in the loop. The wider range cloud providers we test with the better. We've been working on trying to make these sorts of tests easier to manage. I would also encourage them to show up to our sig meeting.

**Comment by caniszczyk** [comment]
@xmudrii we're all set and have the credits deposited already, just need emails to invite to the account, you can reach me at cra at linuxfoundation

**Comment by xmudrii** [comment]
@caniszczyk Sounds great, thank you! I'm sorting some final details with @dims, @cblecker, and SIG-Cloud-Provider and I'll reach out to you as soon as possible.

**Comment by cpanato** [comment]
@cheftako if you need any help to setup things for sig-cloud-provider please let me know, willing to help

**Comment by idvoretskyi** [comment]
@xmudrii please drop me a note when you are ready, we'll sort this out.

**Comment by andrewsykim** [comment]
> Added our sig to the issue. Please keep us in the loop. The wider range cloud providers we test with the better. We've been working on trying to make these sorts of tests easier to manage. I would also encourage them to show up to our sig meeting.

+1, happy to help manage access and what not as needed.

**Comment by xmudrii** [comment]
@caniszczyk @idvoretskyi I've just sent an email to you.

**Comment by xmudrii** [comment]
@cblecker @dims The account has been created and we've got access. From our side, it's okay to close this issue.

**Comment by dims** [comment]
Excellent news!

/close
